# permissions for end users to edit rabbitmqsecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqsecretenginerole-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - rabbitmqsecretengineroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - rabbitmqsecretengineroles/status
  verbs:
  - get
