# permissions for end users to view rabbitmqsecretengineroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqsecretenginerole-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - rabbitmqsecretengineroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - rabbitmqsecretengineroles/status
  verbs:
  - get
