# permissions for end users to view rabbitmqsecretengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqsecretengineconfig-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - rabbitmqsecretengineconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - rabbitmqsecretengineconfigs/status
  verbs:
  - get
