# permissions for end users to edit rabbitmqsecretengineconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rabbitmqsecretengineconfig-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - rabbitmqsecretengineconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - rabbitmqsecretengineconfigs/status
  verbs:
  - get
