apiVersion: redhatcop.redhat.io/v1alpha1
kind: RabbitMQSecretEngineConfig
metadata:
  name: rabbitmqsecretengineconfig-sample
spec:
  authentication: 
    path: kubernetes
    role: rabbitMQ-engine-admin
  path: test-vault-config-operator/rabbitmq
  connectionURI: https://test.com

  # defaultTTL: 1h
  # maxTTL: 24h
