# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/redhatcop.redhat.io_kubernetesauthengineroles.yaml
- bases/redhatcop.redhat.io_policies.yaml
- bases/redhatcop.redhat.io_secretenginemounts.yaml
- bases/redhatcop.redhat.io_databasesecretengineconfigs.yaml
- bases/redhatcop.redhat.io_databasesecretengineroles.yaml
- bases/redhatcop.redhat.io_randomsecrets.yaml
- bases/redhatcop.redhat.io_authenginemounts.yaml
- bases/redhatcop.redhat.io_kubernetesauthengineconfigs.yaml
- bases/redhatcop.redhat.io_passwordpolicies.yaml
- bases/redhatcop.redhat.io_githubsecretengineconfigs.yaml
- bases/redhatcop.redhat.io_githubsecretengineroles.yaml
- bases/redhatcop.redhat.io_rabbitmqsecretengineconfigs.yaml
- bases/redhatcop.redhat.io_rabbitmqsecretengineroles.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_policies.yaml
- patches/webhook_in_secretenginemounts.yaml
- patches/webhook_in_databasesecretengineconfigs.yaml
- patches/webhook_in_databasesecretengineroles.yaml
- patches/webhook_in_randomsecrets.yaml
- patches/webhook_in_authenginemounts.yaml
- patches/webhook_in_kubernetesauthengineconfigs.yaml
# - patches/webhook_in_passwordpolicies.yaml
#- patches/webhook_in_rabbitmqsecretengineconfigs.yaml
#- patches/webhook_in_rabbitmqsecretengineroles.yaml
- patches/webhook_in_rabbitmqsecretengineconfigs.yaml
- patches/webhook_in_rabbitmqsecretengineroles.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_kubernetesauthengineroles.yaml
- patches/cainjection_in_policies.yaml
- patches/cainjection_in_secretenginemounts.yaml
- patches/cainjection_in_databasesecretengineconfigs.yaml
- patches/cainjection_in_databasesecretengineroles.yaml
- patches/cainjection_in_randomsecrets.yaml
- patches/cainjection_in_authenginemounts.yaml
- patches/cainjection_in_kubernetesauthengineconfigs.yaml
# - patches/cainjection_in_passwordpolicies.yaml
#- patches/cainjection_in_githubsecretengineconfigs.yaml
#- patches/cainjection_in_githubsecretengineroles.yaml
- patches/cainjection_in_rabbitmqsecretengineconfigs.yaml
- patches/cainjection_in_rabbitmqsecretengineroles.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
